name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: docker-criterion
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make tests_run
      run: make tests_run
    - name: make fclean
      run: make fclean
